/*
 * Ekubo API Client
 *
 * Сlient for Ekubo AMM DEX. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteResponse {
    Quote(super::quote::Quote),
    Quotes(super::quotes::Quotes),
}

impl Default for QuoteResponse {
    fn default() -> Self {
        Self::Quote(Default::default())
    }
}

